/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author antheabaldacchino
 */
public class Menu extends javax.swing.JFrame
{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
         try {
            //get image from file
            BufferedImage img   = ImageIO.read(new File("waterPoloLogo.png")); 
            
            //scaling it to fit in label container (lblSharkLogo)
            Image scaledImage = img.getScaledInstance(lblSharkLogo.getWidth(),lblSharkLogo.getHeight(), Image.SCALE_SMOOTH); 
            ImageIcon imageIcon   = new ImageIcon(scaledImage);
             //place the image on the lblLogo
            lblSharkLogo.setIcon(imageIcon);
           
        }  catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error loading logo");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSharkLogo = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExitItem = new javax.swing.JMenuItem();
        mnuMembers = new javax.swing.JMenu();
        mnuNewMember = new javax.swing.JMenuItem();
        mnuViewMemebersItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sharks WaterPolo Club");
        setBackground(new java.awt.Color(0, 153, 255));

        lblSharkLogo.setText("jLabel1");

        mnuFile.setText("File");

        mnuExitItem.setText("Exit");
        mnuExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitItemActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExitItem);

        mnuBar.add(mnuFile);

        mnuMembers.setText("Members");

        mnuNewMember.setText("New Member");
        mnuNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewMemberActionPerformed(evt);
            }
        });
        mnuMembers.add(mnuNewMember);

        mnuViewMemebersItem.setText("View All Members");
        mnuViewMemebersItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewMemebersItemActionPerformed(evt);
            }
        });
        mnuMembers.add(mnuViewMemebersItem);

        mnuBar.add(mnuMembers);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblSharkLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblSharkLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitItemActionPerformed
        // TODO add your handling code here:
        int userChoice = JOptionPane.showConfirmDialog(null, "Do you want to exit ?");
        
        if(userChoice == JOptionPane.YES_OPTION){
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitItemActionPerformed

    private void mnuNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewMemberActionPerformed
        // TODO add your handling code here:
        AddNewMember frm = new AddNewMember();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuNewMemberActionPerformed

    private void mnuViewMemebersItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewMemebersItemActionPerformed
        // TODO add your handling code here:
        ViewMembers frm = new ViewMembers();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuViewMemebersItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSharkLogo;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuExitItem;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuMembers;
    private javax.swing.JMenuItem mnuNewMember;
    private javax.swing.JMenuItem mnuViewMemebersItem;
    // End of variables declaration//GEN-END:variables
}
